# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    env:
      GO_VERSION: 1.23.0
      GOLANGCI_LINT_VERSION: v1.61.0
      YAEGI_VERSION: v0.16.1
      GOPATH: ${{ github.workspace }}/go
      CGO_ENABLED: 0
      
    defaults:
      run:
        working-directory: ${{ github.workspace }}/go/src/github.com/${{ github.repository }}
        
    steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}

    - uses: actions/checkout@v4
        with:
          path: go/src/github.com/${{ github.repository }}
          fetch-depth: 0

    - name: Build Cloudflare IPs
      run: bash updateCFIps.sh
      
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
